export const Images = {
  logo: require("./../images/logo.png"),
  white_image: require("./../images/logo.png"),
  addFriend: require("./../images/add_friend.png"),
  launchScreen1: require("./../images/launchscreen1.png"),
  launchScreen2: require("./../images/launchscreen2.png"),
  launchScreen3: require("./../images/launchscreen3.png"),
  launchScreen4: require("./../images/launchscreen4.png"),
  background_image: require("./../images/background_image.png"),
   confirmEmailBg: require("./../images/confirm-email-bg.png"),
  logoFlower: require("./../images/Starbuds-Logo-Concept-1.png"),
  facebook: require("./../images/facebook.png"),
  addprofilebackground: require("./../images/image-icon.png"),
  find_facebook_friend: require("./../images/Artboard.png"),
  addProfilePicture: require("./../images/image-icon.png"),
  username: require("./../images/username.png"),
   mail: require("./../images/mail.png"),
  password: require("./../images/password.png"),
  email: require("./../images/email.png"),
  calender: require("./../images/calender.png"),
  dummyUser: require("./../images/dummyuser.png"),
  smallLogoWithGreenBg: require("./../images/small-logo-with-green-bg.png"),
  blurTest: require("./../images/blurtest.png"),
  settingsIcon: require("./../images/settings icon.png"),
  addUserIcon: require("./../images/add-user-icon.png"),
  gridIconGreen: require("./../images/single-image-icon.png"),
  listIcon: require("./../images/grid-grey.png"),
  saveIcon: require("./../images/bookmark-icon.png"),
  saveIconGreen: require("./../images/save-icon-green.png"),
  starIcon: require("./../images/star-icon.png"),
  starIconGreen: require("./../images/star-icon-green.png"),
  homeTab: require("./../images/home-grey.png"),
  homeTabSelected: require("./../images/home-green.png"),
  searchTab: require("./../images/search-grey.png"),
  searchTabSelected: require("./../images/search-green.png"),
  addPhotoTab: require("./../images/camera-icon.png"),
  addPhotoTabSelected: require("./../images/add_photo_selected.png"),
  activityTab: require("./../images/weed-grey.png"),
  activityTabSelected: require("./../images/activity_selected.png"),
  profileTab: require("./../images/profile.png"),
  profileTabSelected: require("./../images/profile.png"),
  noGroups: require("./../images/noGroup.png"),
  whiteplus: require("./../images/white-plus.png"),
  createGroupPlus: require("./../images/create-group-plus.png"),
  backButton: require("./../images/black-back.png"),
  closeIcon: require("./../images/close.png"),
  closeIconWhite: require('./../images/close-white.png'),
  frontCameraIcon: require("./../images/ic_camera_front_white.png"),
  rearCameraIcon: require("./../images/ic_camera_rear_white.png"),
  autoFlashIcon: require("./../images/ic_flash_auto_white.png"),
  offFlashIcon: require("./../images/ic_flash_off_white.png"),
  onFlashIcon: require("./../images/ic_flash_on_white.png"),
  cameraImage: require("./../images/camera.png"),
  defaultUser: require("./../images/defaultuser.png"),
  blackBackground: require("./../images/blackbg.png"),
  placeHolder: require("./../images/placeholder.png"),
  tagPeopleIcon: require("./../images/tagged-photos-icon.png"),
  sharecontent: require("./../images/sharecontent.png"),
  otherProfileTagPeopleIcon: require("./../images/otherProfileTagPeopleIcon.png"),
  addLocationIcon: require("./../images/location-icon.png"),
  addLocationIconSelected: require("./../images/location-icon-selected.png"),
  closeIconActive: require("./../images/close-icon-active.png"),
  searchLocationIcon: require("./../images/search-location-icon.png"),
  searchIcon: require("./../images/search.png"),
  tagPeopleIconActive: require("./../images/tagged-people-active.png"),
  listIconActive: require("./../images/grid.png"),
  gridIcon: require("./../images/single-image-black-icon.png"),
  rightArrow: require("./../images/right-arrow.png"),
  threeHorizontalDots: require("./../images/3-horizontal-dots.png"),
  blurred: require("./../images/blurred.png"),
  addCircle: require("./../images/add-circle.png"),
  videoRecording: require("./../images/video-recording.png"),
  videoPlay: require("./../images/play-btn.png"),
  videoPause: require("./../images/pause-btn.png"),
  searchPeople: require("./../images/search.png"),
  ellipse: require("./../images/ellipse.png"),
  farmer: require("./../images/farmer.png"),
  videoIcon: require("./../images/video-icon.png"),
  profileBg: require("./../images/profile-bg.png"),
  selectedMultipleImages: require("./../images/selected-multiple-image.png"),
  unSelectedMultipleImages: require("./../images/multiple-image.png"),
  multipleImagesIcon: require("./../images/multiple-image-icon.png"),
  fullScreen:require("./../images/fullscreen.png"),
  sendActive:require('./../images/send-active.png'),
  sendInactive:require('./../images/send-inactive.png'),
  fallbackImage:require('./../images/fallback.jpeg'),
  fallbackVideo:require('./../images/fallback-video.jpg'),
  multipleImages:require('./../images/multi-image.png'),
  saveContent:require('./../images/save-content.png'),
  createGroup: require('./../images/create-group.png'),
  findBudsHeaderIcon:require('./../images/find-bud-header.png'),
  feedLikeInactive:require('./../images/feed-like-inactive.png'),
  feedCommentInactive:require('./../images/comment-grey.png'),
  feedShareInactive:require('./../images/chat-icon-arrow.png'),
  feedSaveInactive:require('./../images/bookmark-icon.png'),
  feedLikeActive:require('./../images/feed-like-active.png'),
  shareIconGreen: require('./../images/feed-share-inactive.png'),
  homeHeaderLeftInActive : require('./../images/home-header-left-leafly.png'),
  homeHeaderLeftActive : require('./../images/home-header-left-leafly.png'),
  shareContentPlus:require('./../images/plusSquare.png'),
  addNewChat: require('./../images/add-new-chat.png'),
  following: require('./../images/following.png'),
  notFollowing: require('./../images/not-following.png'),
  plusIcon: require('./../images/plus.png'),
  chatIcon : require('./../images/chat-icon-arrow.png'),
  chatIconActive : require('./../images/chat-icon-active.png'),
  groupOverlay: require('./../images/group-overlay.png'),
  noActivity: require('./../images/no-activity.png'),
  TWITTER_ICON : require('./../images/twitter.png'),
  FACEBOOK_ICON : require('./../images/facebook-icon.png'),
  WHATSAPP_ICON : require('./../images/whatsapp.png'),
  EMAIL_ICON: require('./../images/email-share.png'),
  noPhotosOfYou: require('./../images/no-photos-of-you.png'),
  noMessages: require('./../images/no-messages.png'),
  news1:require('./../images/news1.png'),
  news2:require('./../images/news2.png'),
  news3:require('./../images/news3.png'),
  Tab1:require('./../images/Tab1.png'),
  Tab2:require('./../images/Tab2.png'),
  Tab3:require('./../images/Tab3.png'),
  Tab4:require('./../images/Tab4.png'),

};
