# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Starbuds' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Fabric'
  pod 'Crashlytics' 
  # Pods for Starbuds

 
end
